"""Interactive init.

The contract: an answer is written only after it has been proven. A command that
did not exit 0 is not recorded as working. The user sees exactly what was
verified, what failed, and what was left out.
"""

from __future__ import annotations

from pathlib import Path

import yaml
from rich.console import Console
from rich.table import Table

from ..config.loader import CONFIG_NAME
from ..config.model import (
    BoundariesConfig,
    CommandsConfig,
    EnvironmentConfig,
    LensConfig,
    ProjectConfig,
    WhetstoneConfig,
)
from ..doctor import _TIMEOUTS, run_command
from .detect import Detection, detect_stack

# Per-label timeouts come from doctor._TIMEOUTS rather than a value copied
# here. `doctor` and `init` verify the same commands; a second, differently
# tuned timeout would let a legitimately slow install that `doctor` accepts
# time out during `init` and be silently left out -- the two tools would then
# disagree about the same command, which is exactly the confusion `init`
# exists to prevent.

# Paths that are almost always someone else's to change. Proposed, not imposed.
_DEFAULT_NEVER_TOUCH = [
    ".github/workflows/**",
    "infra/**",
    "**/migrations/**",
    "**/*.lock",
]

_HEADER = """\
# whetstone.yaml -- generated by `whetstone init`.
#
# Every command below was executed during init and exited 0. Commands that
# failed or were not declared by your project have been left out rather than
# guessed at; add them by hand and re-run `whetstone doctor` to verify.
#
# autonomy: 0 report . 1 propose a spec . 2 open a draft PR . 3 open a PR
# There is no level 4. Whetstone never merges and never deploys.
"""


def build_config(
    project_root: Path,
    detection: Detection,
    *,
    name: str,
    verified: dict[str, bool],
) -> WhetstoneConfig:
    """Assemble a config from *detection*, keeping only verified commands."""
    commands = CommandsConfig(
        **{
            label: command
            for label, command in detection.commands.items()
            if verified.get(label, False)
        }
    )
    return WhetstoneConfig(
        project=ProjectConfig(name=name),
        environment=EnvironmentConfig(commands=commands),
        boundaries=BoundariesConfig(
            include=["**/*"],
            exclude=["**/node_modules/**", "**/dist/**", "**/.venv/**"],
            never_touch=list(_DEFAULT_NEVER_TOUCH),
        ),
        lenses={"hygiene": LensConfig(enabled=True, autonomy=0)},
    )


def render_config(cfg: WhetstoneConfig) -> str:
    body = cfg.model_dump(mode="json", exclude_none=True, exclude_defaults=False)
    return _HEADER + yaml.safe_dump(body, sort_keys=False, allow_unicode=True)


def run_wizard(
    project_root: Path,
    *,
    console: Console | None = None,
    assume_yes: bool = False,
    force: bool = False,
) -> Path:
    console = console or Console()
    target = project_root / CONFIG_NAME
    if target.exists() and not force:
        raise FileExistsError(
            f"{target} already exists. Re-run with --force to overwrite it."
        )

    detection = detect_stack(project_root)
    _print_detection(console, detection)

    verified: dict[str, bool] = {}
    if detection.commands:
        console.print("\n[bold]Verifying declared commands by running them...[/bold]")
        table = Table("command", "result", "detail")
        stdin_closed = False
        for label, command in sorted(detection.commands.items()):
            if label == "dev":
                # Long-running. Recorded but not launched -- M2 verifies it with
                # a readiness probe.
                verified[label] = True
                table.add_row(label, "recorded", "long-running; not launched")
                continue
            if not assume_yes:
                if stdin_closed:
                    verified[label] = False
                    table.add_row(label, "[yellow]skipped[/yellow]", "stdin closed; declined")
                    continue
                try:
                    confirmed = _confirm(console, f"Run `{command}`?")
                except EOFError:
                    # No stdin to ask -- e.g. `init` run in CI or piped without
                    # `--yes`. An unverified command is one the wizard already
                    # leaves out, so a closed stdin is treated the same way as
                    # a declined prompt rather than crashing with a traceback.
                    stdin_closed = True
                    verified[label] = False
                    table.add_row(label, "[yellow]skipped[/yellow]", "stdin closed; declined")
                    continue
                if not confirmed:
                    verified[label] = False
                    table.add_row(label, "[yellow]skipped[/yellow]", "declined")
                    continue
            result = run_command(label, command, project_root, _TIMEOUTS[label])
            verified[label] = result.ok
            table.add_row(
                label,
                "[green]ok[/green]" if result.ok else "[red]failed[/red]",
                result.detail[:80],
            )
        console.print(table)
        if stdin_closed:
            console.print(
                "[yellow]stdin is closed; remaining commands were declined "
                "unattended. Pass --yes to verify automatically instead.[/yellow]"
            )

    cfg = build_config(
        project_root, detection, name=project_root.name, verified=verified
    )
    target.write_text(render_config(cfg), encoding="utf-8")

    omitted = [label for label, ok in verified.items() if not ok]
    console.print(f"\n[green]Wrote {target}[/green]")
    if omitted:
        console.print(
            f"[yellow]Left out (did not verify): {', '.join(sorted(omitted))}."
            " Add them by hand and run `whetstone doctor`.[/yellow]"
        )
    console.print("Next: [bold]whetstone doctor[/bold], then [bold]whetstone run[/bold]")
    return target


def _print_detection(console: Console, detection: Detection) -> None:
    if not detection.languages:
        console.print(
            "[yellow]No recognised project manifest found.[/yellow] "
            "A config will still be written; declare commands by hand."
        )
        return
    table = Table("detected", "value", "why")
    table.add_row("languages", ", ".join(detection.languages), "")
    table.add_row(
        "package manager",
        detection.package_manager or "unknown",
        detection.evidence.get("package_manager", ""),
    )
    for label, command in sorted(detection.commands.items()):
        table.add_row(f"command: {label}", command, "from project manifest")
    console.print(table)
    # A polyglot repo can detect commands it then does not use -- see
    # detect.py's `_detect_node`. Told, not silently dropped.
    for key, note in sorted(detection.evidence.items()):
        if key.endswith("_commands_unused"):
            console.print(f"[yellow]{note}[/yellow]")


def _confirm(console: Console, question: str) -> bool:
    answer = console.input(f"{question} [Y/n] ").strip().lower()
    return answer in ("", "y", "yes")
